# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'', width_field=b'width_field'),
        ),
    ]
